### ISSUE TITLE
Use SSL

### ISSUE THREAD

**Issue by Feliix42** [kiliankoe/fachschaftsr.at#1]
Especially in these rough days it's important to make sure that _this_ web site uses https, since you are delivering very confidential content!

**Comment by kiliankoe** [comment]
That's odd, SSL should actually be working. Not quite sure yet what to do with the site, so I just threw it onto github pages based hosting of an essentially empty index.html. DNS is managed via Cloudflare, which should've enabled their SSL... I'll have a look^^

Should you have any ideas what to do with this, please tell me 😃

**Comment by Feliix42** [comment]
Wow, didn't suspect you already added SSL support 😄 
When i open https://fachschaftsr.at, I see an `Error 522` :(

**Comment by kiliankoe** [comment]
Let's just wait a bit and see if it works out^^ If it's still throwing errors tomorrow I'll have another look 😄

**Comment by kiliankoe** [comment]
Working, but not enforced yet :(

**Comment by kiliankoe** [comment]
now enforced, nice
